default_agent: alarming
agents:
  alarming:
    name: alarming
    entrypoint: agent.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::129463259399:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-911561122e
      execution_role_auto_create: false
      account: '129463259399'
      region: us-east-1
      ecr_repository: 129463259399.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-alarming
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: alarming-qq33p96PFS
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:129463259399:runtime/alarming-qq33p96PFS
      agent_session_id: ee9637a4-cdb3-4d90-a2a0-e67fcfa17d36
    codebuild:
      project_name: bedrock-agentcore-alarming-builder
      execution_role: arn:aws:iam::129463259399:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-911561122e
      source_bucket: bedrock-agentcore-codebuild-sources-129463259399-us-east-1
    authorizer_configuration: null
    oauth_configuration: null
