default_agent: discovery
agents:
  discovery:
    name: discovery
    entrypoint: agent.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::129463259399:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-fa44132b23
      execution_role_auto_create: false
      account: '129463259399'
      region: us-east-1
      ecr_repository: 129463259399.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-discovery
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: discovery-TbhTOu3vU7
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:129463259399:runtime/discovery-TbhTOu3vU7
      agent_session_id: dd6e2022-b8a4-4448-a937-79279f7bc17d
    codebuild:
      project_name: bedrock-agentcore-discovery-builder
      execution_role: arn:aws:iam::129463259399:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-fa44132b23
      source_bucket: bedrock-agentcore-codebuild-sources-129463259399-us-east-1
    authorizer_configuration: null
    oauth_configuration: null
