default_agent: reporting
agents:
  reporting:
    name: reporting
    entrypoint: agent.py
    platform: linux/arm64
    container_runtime: none
    aws:
      execution_role: arn:aws:iam::129463259399:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-637d7becb9
      execution_role_auto_create: false
      account: '129463259399'
      region: us-east-1
      ecr_repository: 129463259399.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-reporting
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: reporting-r7Ph58CwkW
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:129463259399:runtime/reporting-r7Ph58CwkW
      agent_session_id: 3ad3d67f-ed1d-4d51-9200-1ee0843f0679
    codebuild:
      project_name: bedrock-agentcore-reporting-builder
      execution_role: arn:aws:iam::129463259399:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-637d7becb9
      source_bucket: bedrock-agentcore-codebuild-sources-129463259399-us-east-1
    authorizer_configuration: null
    oauth_configuration: null
