default_agent: investigator
agents:
  investigator:
    name: investigator
    entrypoint: agent.py
    platform: linux/amd64
    container_runtime: docker
    aws:
      execution_role: null
      execution_role_auto_create: true
      account: '129463259399'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: true
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: b9af8c32-7342-4cc1-86b9-4714618adf0d
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    authorizer_configuration: null
    oauth_configuration:
      workload_name: workload-82871e6f
