default_agent: investigator
agents:
  investigator:
    name: investigator
    entrypoint: agent.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::129463259399:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-ea077ff913
      execution_role_auto_create: false
      account: '129463259399'
      region: us-east-1
      ecr_repository: 129463259399.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-investigator
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: investigator-JB4TCCB1ao
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:129463259399:runtime/investigator-JB4TCCB1ao
      agent_session_id: 540816ca-63f0-48e0-89b4-0a7ce7f3bda8
    codebuild:
      project_name: bedrock-agentcore-investigator-builder
      execution_role: arn:aws:iam::129463259399:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-ea077ff913
      source_bucket: bedrock-agentcore-codebuild-sources-129463259399-us-east-1
    authorizer_configuration: null
    oauth_configuration:
      workload_name: workload-82871e6f
